# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# Ensure xdg-desktop-portal starts (graphical-session.target doesn't activate on Hyprland)
exec-once = /usr/lib/xdg-desktop-portal
